### ISSUE TITLE
SPARQL 1.1 Federation Not Recognized

### ISSUE THREAD

**Issue by schivmeister** [protegeproject/snap-sparql-query#26]
First of all this will fail because the plug-in expects an explicit WHERE:

```
select * {
  service <https://query.wikidata.org/sparql> { 
    ?s a owl:Class .
  }
} limit 10
```

So OK, fix that and we also make sure every keyword is uppercase in case that was a thing:

```
SELECT * WHERE {
  SERVICE <https://query.wikidata.org/sparql> { 
    ?s a owl:Class .
  }
} LIMIT 10
```

Now the plug-in complains about SERVICE being an unexpected keyword. SPARQL 1.1 Federation is a key feature of SPARQL 1.1. @matthewhorridge Your SNAP paper makes no explicit mention of Federation _not_ being supported so are we not supposed to assume there _is_ support? http://cgi.csc.liv.ac.uk/~valli/OWLED2015/OWLED_2015_paper_21.pdf

If not, can we ever expect to have this support, or is it too much and users should just pick any other tool if they needed a bit more than simple SELECT queries?

**Comment by matthewhorridge** [comment]
@schivmeister it's not supported and, unfortunately, will never be supported due to priorities elsewhere.  SNAP also is intended to simply query the ontologies that are open in Protege (and their entailments), so your last point is spot on.
