### ISSUE TITLE
Variables are not allowed as predicates

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/snap-sparql-query#9]
This very simple example fails to run:
```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?s ?p
    WHERE { 
         ?s ?p owl:Thing.
   }
```

Apparently the plug-in does not like to have `?p` as the predicate of the triple, although the error message itself suggests that it is one of the things it expects:
```
Encountered ?p at line 7 column 13. Expected one of:
    Variable
    Object property name (prefixed name)
    owl:equivalentProperty
    ...
```

**Comment by tudorache** [comment]
It does, it just requires all variables to be typed. Here is Matthew's answer:

"All of the variables should be typed - SNAP allows some implicit typing based on information in the ontology and in the query, but in this case ?p could be either an object, data or annotation property.  If you are looking for object property assertions and you add ?p rdf:type owl:ObjectProperty then this should work."

The typing of variables is part of the spec:
http://www.w3.org/TR/sparql11-entailment/#VarTyping

**Comment by matthewhorridge** [comment]
Variables are allowed as predicates, but in this case you need to add a type for the variable ?p to make it a well-formed query.  e.g.

```ttl
SELECT ?p ?o 
WHERE 
{	
		?p a owl:ObjectProperty .
		:Mick ?p ?o.
}
```

[One of the requirements of the spec](http://www.w3.org/TR/sparql11-entailment/#VarTyping) is that variables are typed.  Snap is, in general, a bit lenient with this if it can figure out the types of variables from the background ontology or their position in the query (in the case above now, ?o must be an individual variable), but in your original query it's not possible to do that - ?p could be an object, data or annotation property variable.

If you want both object and data properties in the results then you can do a union e.g.

```ttl
SELECT ?p ?o 
WHERE 
{

	{	
		?p a owl:ObjectProperty .
		:Mick ?p ?o.
	}
	
	UNION
	{
		?p a owl:DatatypeProperty .
		:Mick ?p ?o.
	}
}
```
In case you'r wondering, here, in the first group graph pattern ?o will be an individual variable, and in the second ?o will be a literal variable - different groups can type variables differently.

**Comment by matthewhorridge** [comment]
Thanks @tudorache - I was typing this out in parallel!

**Comment by tudorache** [comment]
Yes, collaborative editing :)

**Comment by matthewhorridge** [comment]
Ah, I love Github conversations :)

**Comment by csnyulas** [comment]
Two answers are better than one.
Thank you both!

**Comment by csnyulas** [comment]
I still have an issue:
Given [this ontology](https://github.com/protegeproject/snap-sparql-query/files/267100/test_sparql.owl.zip), this works:
```
PREFIX : <http://www.semanticweb.org/ttania/ontologies/2016/4/untitled-ontology-8#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?s ?p ?o
    WHERE { 
        ?s rdf:type :Person.
   }
```
and even this works
```
PREFIX : <http://www.semanticweb.org/ttania/ontologies/2016/4/untitled-ontology-8#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?s ?p ?o
    WHERE { 
        ?s rdf:type :Person.
	?p rdf:type owl:DatatypeProperty.
   }
```
But this does not:
```
PREFIX : <http://www.semanticweb.org/ttania/ontologies/2016/4/untitled-ontology-8#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?s ?p ?o
    WHERE { 
        ?s rdf:type :Person.
	?p rdf:type owl:DatatypeProperty.
	?s ?p ?o          
   }
```

**Comment by matthewhorridge** [comment]
I get the following results...  When you say "works" what do you mean?  Do you get any results?

<img width="1173" alt="snap" src="https://cloud.githubusercontent.com/assets/488607/15306940/97ac3c12-1b83-11e6-808b-872eddd7ceb2.png">

**Comment by csnyulas** [comment]
I do not get back any results:
![screenshot from 2016-05-16 17 09 20](https://cloud.githubusercontent.com/assets/2441046/15307548/0bcacbea-1b89-11e6-8cff-9aa978f0a991.png)

**Comment by csnyulas** [comment]
I figured it out. It was the Fact++ reasoner that does not return any results. Hermit and Pellet works. Even no reasoner works.
